```{r Settings, warning=F, message=F}
#Settings
# library("spatialfil")
# library("ggplot2")
# library("papaja")
# library("msm")
# library("shape")
# library("mvtnorm")
# library("tmvtnorm")
# library("cowplot")
# library("gridExtra")

theme_set(theme_apa(base_size = 22))
rotate <- function(x) t(apply(x, 2, rev))

sd0 <- .09
eta = .6

gamma <- seq(-.25, .25, .0025)

kern <- convKernel(sigma = 8, k = "gaussian")
kernUni <- convKernel(sigma = 2, k = "gaussian")

nrmlz <- function(mat)
{
  tot <- sum(mat)
  mat/tot
}

#Conditional model specification
norm0 <- function(theta1, theta2, Sigma) dnorm(theta1, 0,Sigma) * dnorm(theta2, 0, Sigma)
norm <- function(theta1, theta2, Sigma) dmvnorm(cbind(theta1, theta2), c(0,0), Sigma)
normT1 <- function(theta1, theta2, Sigma, l, u) dtmvnorm(cbind(theta1, theta2)
                                                   , c(0,0)
                                                   , Sigma
                                                   , lower = rep(l, 2)
                                                   , upper = rep(u, 2))
normT <- function(theta1, theta2, Sigma, l , u){
  dtnorm(theta1, 0, Sigma, lower = l, upper = u) * dtnorm(theta2, 0, Sigma, lower = l, upper = u)
}

observed <- data.frame(Delta1 = .07, Delta2 = .05)

#Setup ggplot dataframes
probs = c(.5, .7, .9, .95)
myPalette <- rev(c(paste0("grey", round(100*seq(.1, .9, .05)))))

combiDeltas <- expand.grid(
  Delta1 = gamma
  , Delta2 = gamma
  , figType = c("Model", "Prediction")
  , Model = c("Null Model", "Common-effect Model", "Positive-effects Model", "Negative-effects Model", "Spike-and-Slab Model", "Unconstrained Model")
)
combiDeltas$Density <- NA

combiDeltasRaw <- expand.grid(
  Delta1 = gamma
  , Delta2 = gamma
)

#ggplot skeleton
makeModelPlot <- function(z, dat, ylab, xlab = NULL, breaks, strip = FALSE, ypos = "left", last = F){
  graycols <- gray.colors(100, max(.0, .6 - 100 * max(dat$Density))
                          , max(.7, 1 - 50 * max(dat$Density)))
  margins <- c(5, 0, -10, 12)
  margins_last <- c(5, 0, 0, 12)
  # breaks <- exp(c(-11:(-1), -.1))
  ggplot(mapping = aes(y = Delta1, x = Delta2, z = eval(parse(text = z)), fill = ..level..)
         , data = dat
         ) +
  # geom_tile(aes(fill = predDensityCookLewandowski)) +
  stat_contour(geom = "polygon"
               # , breaks = breaks
  ) +
  geom_hline(yintercept = 0, color = "grey70", size = .3, alpha = .3) +
  geom_vline(xintercept = 0, color = "grey70", size = .3, alpha = .3) +
  geom_point(data = observed
             , mapping = aes(x = Delta2, y = Delta1)
             , inherit.aes = FALSE
             , color = ifelse(ypos == "right", "#E41A1C", adjustcolor("white", alpha.f = 0))) + 
  scale_fill_gradientn(colors = rev(graycols)) +
  # coord_fixed() +
  scale_y_continuous(position = ypos
                     , limits = c(min(combiDeltas$Delta1), max(combiDeltas$Delta1))
                     , breaks = seq(-.2, .2, length.out = 3)
                     , labels = seq(-200, 200, length.out = 3)
                     ) +
  scale_x_continuous(breaks = seq(-.2, .2, length.out = 3)
                     , limits = c(min(combiDeltas$Delta2), max(combiDeltas$Delta2))
                     , labels = seq(-200, 200, length.out = 3)
                     ) +
  labs(x = xlab, y = ylab) +
  # facet_grid(Model ~ figType) + 
  theme(
    legend.position = "none"
    , axis.title.x = if(!is.expression(xlab)) element_blank() else element_text()
    , axis.text.x = if(!is.expression(xlab)) element_blank() else element_text()
    , axis.ticks.x = if(!is.expression(xlab)) element_blank() else element_line()
    , axis.text.y = if(!is.expression(ylab)) element_text(colour = "white") else element_text()
    , axis.ticks.y = if(!is.expression(ylab)) element_blank() else element_line()
    , strip.text.x = if(!strip) element_blank() else element_text()
    # , panel.border = element_rect(color = "black", fill = NA)
    , axis.text.y.right = element_text(hjust = 1)
    # , panel.spacing = unit(10, "points")
    # , panel.spacing = unit(rel(10), "points")
    , strip.text.y = ggplot2::element_text(margin = ggplot2::margin(0, 0, 0, 0))
    , axis.title.y = element_text(margin = margin(t = 0, r = 0, b = 0, l = 0))
    # , plot.margin = unit(if(last == T){margins_last}else{margins}, "points")
    # , strip.text.y = ggplot2::element_text(margin = ggplot2::margin(0, 0, 0, ggplot2::rel(12)))
  )
}

univarModelPlot <- function(y, dat, xlab = NULL
                            , arrowPos = data.frame(x1 = 0, x2 = 0, y1 = 0, y2 = 0)
                            , ylim){
  margins <- c(5, 0, 0, 12)
  ggplot(mapping = aes(x = theta, y = eval(parse(text = y))), data = dat) +
  geom_line() +
  labs(x = "", #xlab,
       y = "") +
  geom_segment(data = arrowPos
               , mapping = aes(x = x1, xend = x2
                               , y = y1,  yend = y2)
               , arrow = arrow(length = unit(0.15,"cm")
                               , angle = 25
                               , type = "closed"
                               )
               , show.legend=FALSE
               , color = ifelse(arrowPos$y2 == 0, "white", "black")) +
  scale_y_continuous(limits = ylim, breaks = NULL) +
  scale_x_continuous(breaks = NULL) +
  theme(plot.title = element_text(size = rel(1), hjust = 0.5)
        # , axis.text.y = element_blank()
        # , axis.ticks.y = element_blank()
        , legend.position = "none"
        , plot.margin = unit(margins, "points"))
}
```

```{r densities, cache = T}
Null <- outer(gamma, gamma, norm0, Sigma = .002)
Null <- nrmlz(Null)
One <- outer(gamma
                   , gamma
                   , normT1
                   , Sigma = matrix(c(sd0^2, sd0^2.0002, sd0^2.0002, sd0^2)
                                    , nrow = 2)
                   , l = 0
                   , u = Inf) 
One <- nrmlz(One)
Pos <- outer(gamma
                   , gamma
                   , normT
                   , sd0
                   , l = 0
                   , u = Inf)
Pos <- nrmlz(Pos)
Neg <- outer(gamma
                   , gamma
                   , normT
                   , sd0
                   , l = -Inf
                   , u = 0)
Neg <- nrmlz(Neg)
General <- outer(gamma
                 , gamma
                 , norm
                 , Sigma = matrix(c(sd0^2, 0, 0, sd0^2)
                                  , nrow = 2))
General <- nrmlz(General)

priorPos1 <- outer(gamma
                   , gamma
                   , normT1
                   , Sigma = matrix(ncol = 2, c(sd0^2, 0, 0, .005^2))
                   , l = 0
                   , u = Inf)
priorPos1 <- nrmlz(priorPos1)

priorPos2 <- outer(gamma
                   , gamma
                   , normT1
                   , Sigma = matrix(ncol = 2, c(.005^2, 0, 0, sd0^2))
                   , l = 0
                   , u = Inf)
priorPos2 <- nrmlz(priorPos2)

priorSpike <- outer(gamma
                   , gamma
                   , normT1
                   , Sigma = matrix(ncol = 2, c(.005^2, 0, 0, .005^2))
                   , l = 0
                   , u = Inf)
priorSpike <- nrmlz(priorSpike)

Mix <- .0 * priorSpike + .5 * priorPos1 + .5 * priorPos2 + 7 * Pos
Mix <- nrmlz(Mix)

#Marginal model specification
GeneralH <- outer(gamma
                  , gamma
                  , norm
                  , Sigma = matrix(c(sd0^2, eta*sd0^2, eta*sd0^2, sd0^2)
                                     , nrow = 2))
GeneralH <- nrmlz(GeneralH)

PosH <- 4 * GeneralH
index <- gamma < 0
PosH[index, ] <- 0
PosH[, index] <- 0
PosH <- nrmlz(PosH)

NegH <- 4 * GeneralH
index <- gamma > 0
NegH[index, ] <- 0
NegH[, index] <- 0
NegH <- nrmlz(NegH)

MixH <- .0 * priorSpike + .6 * priorPos1 + .6 * priorPos2 + 8 * PosH
MixH <- nrmlz(MixH)

#Model Predictions
NullP <- nrmlz(applyFilter(Null, kern))
OneP <- nrmlz(applyFilter(One, kern))
PosP <- nrmlz(applyFilter(PosH, kern))
NegP <- nrmlz(applyFilter(NegH, kern))
GeneralP <- nrmlz(applyFilter(GeneralH, kern))
MixP <- 0 * priorSpike + .8 * priorPos1 + .8 * priorPos2 +  2*PosH
MixP <- nrmlz(applyFilter(MixP, kern))
```

```{r null_model_prediction_plot, warning = FALSE}
combiDeltas[combiDeltas$figType == "Model" & combiDeltas$Model == "Null Model", "Density"] <- as.vector(Null)
combiDeltas[combiDeltas$figType == "Prediction" & combiDeltas$Model == "Null Model", "Density"] <- as.vector(NullP)

nullmod <- data.frame(x = 0, y = 0, figType = "Model")
```

```{r common_model_prediction_plot, cache = TRUE}
combiDeltas[combiDeltas$figType == "Model" & combiDeltas$Model == "Common-effect Model", "Density"] <- as.vector(One)
combiDeltas[combiDeltas$figType == "Prediction" & combiDeltas$Model == "Common-effect Model", "Density"] <- as.vector(OneP)
```

```{r positive_model_prediction_plot, cache = TRUE}
combiDeltas[combiDeltas$figType == "Model" & combiDeltas$Model == "Positive-effects Model", "Density"] <- as.vector(PosH) * 1.7
combiDeltas[combiDeltas$figType == "Prediction" & combiDeltas$Model == "Positive-effects Model", "Density"] <- as.vector(PosP) * 1.5
```

```{r negative_model_prediction_plot, cache = TRUE}
combiDeltas[combiDeltas$figType == "Model" & combiDeltas$Model == "Negative-effects Model", "Density"] <- as.vector(NegH)
combiDeltas[combiDeltas$figType == "Prediction" & combiDeltas$Model == "Negative-effects Model", "Density"] <- as.vector(NegP)
```

```{r sns_model_prediction_plot, cache = TRUE}
combiDeltas[combiDeltas$figType == "Model" & combiDeltas$Model == "Spike-and-Slab Model", "Density"] <- as.vector(MixH) * 1.6
combiDeltas[combiDeltas$figType == "Prediction" & combiDeltas$Model == "Spike-and-Slab Model", "Density"] <- as.vector(MixP)
```

```{r general_model_prediction_plot, cache = TRUE}
combiDeltas[combiDeltas$figType == "Model" & combiDeltas$Model == "Unconstrained Model", "Density"] <- as.vector(GeneralH) * .9
combiDeltas[combiDeltas$figType == "Prediction" & combiDeltas$Model == "Unconstrained Model", "Density"] <- as.vector(GeneralP) * .8
```

```{r cache = T}
noise <- function(theta, sd) dnorm(theta, 0, sd)   
tTruth <- function(theta, upper = Inf, lower = 0, sd){
  dtnorm(theta, 0, sd0, upper = upper, lower = lower)  
}

arrowPos <- data.frame(x1 = 0, x2 = 0
                       , y1 = 0 #max(tTruth(gamma)) + 2
                       , y2 = max(nrmlz(tTruth(gamma, sd = sd0))) + .01)

lims <- c(0, arrowPos$y2)

model <- rep(c("Null", "Positive", "Negative", "General", "SnS"), each = length(gamma))
modelDens <- data.frame(model = model, theta = rep(gamma, 5), density = NA, prediction = NA)

modelDens[model == "Null", ]$density <- rep(0, length(gamma))
modelDens[model == "Null", ]$prediction <- colSums(NullP)
modelDens[model == "Positive", ]$density <- nrmlz(tTruth(gamma, sd = sd0))
modelDens[model == "Positive", ]$prediction <- colSums(PosP)
modelDens[model == "Negative", ]$density <- nrmlz(tTruth(gamma, sd = sd0, upper = 0, lower = -Inf))
modelDens[model == "Negative", ]$prediction <- colSums(NegP)
modelDens[model == "General", ]$density <- nrmlz(tTruth(gamma, sd = sd0, lower = -Inf))
modelDens[model == "General", ]$prediction <- colSums(GeneralP)
modelDens[model == "SnS", ]$density <- nrmlz(tTruth(gamma, sd = sd0)) * .5
modelDens[model == "SnS", ]$prediction <- colSums(PosP) * .7 + colSums(NullP) * .5
 
UniNull <- univarModelPlot("density", subset(modelDens, model == "Null")
                           , arrowPos = arrowPos, ylim = lims, xlab = expression(theta))
UniNullP <- univarModelPlot("prediction", subset(modelDens, model == "Null")
                           , ylim = c(0, .058), xlab = expression(hat(theta)))

UniPos <- univarModelPlot("density", subset(modelDens, model == "Positive")
                           , ylim = lims, xlab = expression(theta))
UniPosP <- univarModelPlot("prediction", subset(modelDens, model == "Positive")
                           , ylim = lims, xlab = expression(hat(theta)))

UniNeg <- univarModelPlot("density", subset(modelDens, model == "Negative")
                           , ylim = lims, xlab = expression(theta))
UniNegP <- univarModelPlot("prediction", subset(modelDens, model == "Negative")
                           , ylim = lims, xlab = expression(hat(theta)))

UniGen <- univarModelPlot("density", subset(modelDens, model == "General")
                           , ylim = lims, xlab = expression(theta))
UniGenP <- univarModelPlot("prediction", subset(modelDens, model == "General")
                           , ylim = lims, xlab = expression(hat(theta)))

UniSnS <- univarModelPlot("density", subset(modelDens, model == "SnS")
                           , arrowPos = arrowPos * .8, ylim = lims, xlab = expression(theta))
UniSnSP <- univarModelPlot("prediction", subset(modelDens, model == "SnS")
                           , ylim = lims, xlab = expression(hat(theta)))
```

```{r ModelFig, fig.align='center', fig.width = 5, fig.height =9, out.height="8in", fig.cap = "Models (left) and predictions (right) for the symbolic distance effect. Darker areas represent higher plausibility of $\\Delta_{im}$ before the data are collected.  Models are conditional on set values of $\\mu_m=0$ms and $\\eta=90$ms. Predictions take into account sampling noise and the correlation reflects the priors placed on $\\mu_m$ and $\\eta^2$. The red point represents a hypothetical observed data point for two individuals. The hypothetical data point is best predicted by the Analog-Representaion model."}

No.m <- makeModelPlot(z = "Density"
                        , dat = subset(combiDeltas
                                       , Model == "Null Model" & figType == "Model") * .001
                        , ylab = expression(paste(theta[2]))
                        , xlab = expression(paste(theta[1]))
                        , breaks = rev(breaksEq)
                        , strip = TRUE)

Null.m <- makeModelPlot(z = "Density"
                          , dat = subset(combiDeltas
                                         , Model == "Null Model" & figType == "Model")
                          , ylab = expression(paste(theta["2"]))
                          , xlab = expression(paste(theta["1"]))
                          , breaks = rev(breaksEq)
                          , strip = TRUE
                        , last = T) +
  geom_point(data = nullmod
             , mapping = aes(x = x, y = y)
             , inherit.aes = FALSE
             , color = "grey10")

One.m <- makeModelPlot(z = "Density"
                                , dat = subset(combiDeltas
                                               , Model == "Common-effect Model" & figType == "Model")
                                , ylab = expression(paste(theta["2"]))
                                , xlab = expression(paste(theta["1"]))
                                , breaks = rev(breaks)
                       , last = T)

Pos.m <- makeModelPlot(z = "Density"
                                , dat = subset(combiDeltas
                                               , Model == "Positive-effects Model" & figType == "Model")
                                , ylab = expression(paste(theta["2"]))
                                , xlab = expression(paste(theta["1"]))
                                , breaks = rev(breaks)
                       , last = T)

SnS.m <- makeModelPlot(z = "Density"
                                , dat = subset(combiDeltas
                                               , Model == "Spike-and-Slab Model" & figType == "Model")
                                , ylab = expression(paste(theta["2"]))
                                , xlab = expression(paste(theta["1"]))
                                , breaks = rev(breaks)
                       , last = T)

General.m <- makeModelPlot(z = "Density"
                           , dat = subset(combiDeltas
                                          , Model == "Unconstrained Model" & figType == "Model")
                           , ylab = expression(paste(theta["2"]))
                           , xlab = expression(paste(theta["1"]))
                           , breaks = rev(breaks)
                           , last = T)

Null.p <- makeModelPlot(z = "Density"
                          , dat = subset(combiDeltas
                                         , Model == "Null Model" & figType == "Prediction")
                          , ylab = expression(paste(hat(theta)["2"]))
                           , xlab = expression(paste(hat(theta)["1"]))
                          , breaks = rev(breaksEq)
                          , strip = TRUE
                          )

One.p <- makeModelPlot(z = "Density"
                          , dat = subset(combiDeltas
                                        , Model == "Common-effect Model" & figType == "Prediction")
                                , ylab = expression(paste(hat(theta)["2"]))
                           , xlab = expression(paste(hat(theta)["1"]))
                                , breaks = rev(breaks)
                                )

Pos.p <- makeModelPlot(z = "Density"
                                , dat = subset(combiDeltas
                                      , Model == "Positive-effects Model" & figType == "Prediction")
                                , ylab = expression(paste(hat(theta)["2"]))
                           , xlab = expression(paste(hat(theta)["1"]))
                                , breaks = rev(breaks)
                                )

SnS.p <- makeModelPlot(z = "Density"
                                , dat = subset(combiDeltas
                                      , Model == "Spike-and-Slab Model" & figType == "Prediction")
                                , ylab = expression(paste(hat(theta)["2"]))
                           , xlab = expression(paste(hat(theta)["1"]))
                                , breaks = rev(breaks)
                                )

General.p <- makeModelPlot(z = "Density"
                           , dat = subset(combiDeltas
                                          , Model == "Unconstrained Model" & figType == "Prediction")
                           , ylab = expression(paste(hat(theta)["2"]))
                           , xlab = expression(paste(hat(theta)["1"]))
                           , breaks = rev(breaks)
                           , last = T)

rerun.fig <- function(){
Null.m <- makeModelPlot(z = "Density"
                          , dat = subset(combiDeltas
                                         , Model == "Null Model" & figType == "Model")
                          , ylab = expression(paste(theta["2"]))
                          , xlab = expression(paste(theta["1"]))
                          , breaks = rev(breaksEq)
                          , strip = TRUE
                        , last = T) +
  geom_point(data = nullmod
             , mapping = aes(x = x, y = y)
             , inherit.aes = FALSE
             , color = "grey10")

One.m <- makeModelPlot(z = "Density"
                                , dat = subset(combiDeltas
                                               , Model == "Common-effect Model" & figType == "Model")
                                , ylab = expression(paste(theta["2"]))
                                , xlab = expression(paste(theta["1"]))
                                , breaks = rev(breaks)
                       , last = T)

Pos.m <- makeModelPlot(z = "Density"
                                , dat = subset(combiDeltas
                                               , Model == "Positive-effects Model" & figType == "Model")
                                , ylab = expression(paste(theta["2"]))
                                , xlab = expression(paste(theta["1"]))
                                , breaks = rev(breaks)
                       , last = T)

SnS.m <- makeModelPlot(z = "Density"
                                , dat = subset(combiDeltas
                                               , Model == "Spike-and-Slab Model" & figType == "Model")
                                , ylab = expression(paste(theta["2"]))
                                , xlab = expression(paste(theta["1"]))
                                , breaks = rev(breaks)
                       , last = T)

General.m <- makeModelPlot(z = "Density"
                           , dat = subset(combiDeltas
                                          , Model == "Unconstrained Model" & figType == "Model")
                           , ylab = expression(paste(theta["2"]))
                           , xlab = expression(paste(theta["1"]))
                           , breaks = rev(breaks)
                           , last = T)

Null.p <- makeModelPlot(z = "Density"
                          , dat = subset(combiDeltas
                                         , Model == "Null Model" & figType == "Prediction")
                          , ylab = expression(paste(hat(theta)["2"]))
                           , xlab = expression(paste(hat(theta)["1"]))
                          , breaks = rev(breaksEq)
                          , strip = TRUE
                          )

One.p <- makeModelPlot(z = "Density"
                          , dat = subset(combiDeltas
                                        , Model == "Common-effect Model" & figType == "Prediction")
                                , ylab = expression(paste(hat(theta)["2"]))
                           , xlab = expression(paste(hat(theta)["1"]))
                                , breaks = rev(breaks)
                                )

Pos.p <- makeModelPlot(z = "Density"
                                , dat = subset(combiDeltas
                                      , Model == "Positive-effects Model" & figType == "Prediction")
                                , ylab = expression(paste(hat(theta)["2"]))
                           , xlab = expression(paste(hat(theta)["1"]))
                                , breaks = rev(breaks)
                                )

SnS.p <- makeModelPlot(z = "Density"
                                , dat = subset(combiDeltas
                                      , Model == "Spike-and-Slab Model" & figType == "Prediction")
                                , ylab = expression(paste(hat(theta)["2"]))
                           , xlab = expression(paste(hat(theta)["1"]))
                                , breaks = rev(breaks)
                                )

General.p <- makeModelPlot(z = "Density"
                           , dat = subset(combiDeltas
                                          , Model == "Unconstrained Model" & figType == "Prediction")
                           , ylab = expression(paste(hat(theta)["2"]))
                           , xlab = expression(paste(hat(theta)["1"]))
                           , breaks = rev(breaks)
                           , last = T)

scaler <- 1.2

align_plots(Null.m
          , Null.p
          , One.m
          , One.p
          , Pos.m
          , Pos.p
          , SnS.m
          , SnS.p
          , General.m
          , General.p
          , align = "h"
          , axis = 'l')
}
# 
# plot_grid(plots[[1]]
#           , plots[[2]]
#           , plots[[3]]
#           , plots[[4]]
#           , plots[[5]]
#           , plots[[6]]
#           , plots[[7]]
#           , plots[[8]]
#           , ncol = 2
#           # , hjust = rep(c(-6, -1), 4)
#           , rel_widths = c(.495, .505)
#           # , rel_heights = c(1/4, rep(1/4 * scaler, 2), 1/4 * 1.1)
#           , labels="AUTO"
#           # , align = "hv"
#           )

plots <- rerun.fig()
```

```{r combine, fig.asp = 1, fig.width=8}
beautyPlot <- function(uniPlot, multiPlot, title = ""){
  first_col <- plot_grid(uniPlot + theme(plot.margin = unit(c(0., 0, 0, 2.2), "cm")) +
                         geom_hline(yintercept = c(0)) 
          , multiPlot + theme(plot.margin = unit(c(0, 0, 0.5, 0.5), "cm")) +
            ggtitle(title) + theme(plot.title = element_text(size = 10, margin = margin(b = -10)))
          , ncol = 1
          , rel_heights = c(1, 3)
          )
  second_col <- plot_grid(NULL
          , uniPlot + coord_flip() + theme(plot.margin = unit(c(0, 0, 1.6, 0), "cm")) +
                         geom_hline(yintercept = c(0))
          , ncol = 1
          , rel_heights = c(1, 3)
          )
  perfect <- plot_grid(first_col, second_col, ncol = 2, rel_widths = c(3, 1))
  return(perfect)
}

# beautyPlot(UniGen, General.m)
# beautyPlot(UniNeg, Neg.m)
# beautyPlot(UniNegP, Neg.p)
```


